// Code generated by tygo. DO NOT EDIT.
/**
 * GENERATED FILE — do not edit.
 *
 * Produced by `mise run gen` from internal/service/apitypes.go, which is
 * the source of truth for every shape the API returns. Edit the Go
 * structs, then re-run generation; CI checks this file is current.
 */
/* eslint-disable */

/**
 * The six first-class document types. The server only ever emits these:
 * a frontmatter `type:` outside the set is ignored in favour of the
 * directory the file lives in.
 */
export type DocType =
  "note" | "person" | "company" | "project" | "meeting" | "daily";

//////////
// source: apitypes.go
/*
The wire contract: every shape the HTTP API and MCP tools return lives
here, and nowhere else. `mise run gen` runs tygo over THIS FILE ONLY to
produce web/src/api/generated.ts, so the frontend's types cannot drift
from the server's — a field renamed here fails the frontend typecheck.

Keep this file to plain data: no methods, no unexported fields, no types
the browser never sees.
*/

/**
 * DocMeta is a document's listing metadata.
 */
export interface DocMeta {
  path: string;
  type: DocType;
  title: string;
  mtime: string;
  sha256: string;
  tags: string[];
  /**
   * Area is the document's frontmatter area:, lowercased; "" when
   * unclassified. Daily notes are always "".
   */
  area: string;
}
/**
 * AreaCount is one area (work, personal, …) with its document count.
 */
export interface AreaCount {
  area: string;
  count: number /* int */;
}
/**
 * Link is a wikilink with its resolution ("" target = dangling → null).
 */
export interface Link {
  target: string | null;
  raw: string;
  display: string;
}
/**
 * Document is the full read payload.
 */
export interface Document extends DocMeta {
  markdown: string;
  frontmatter: { [key: string]: any };
  links: Link[];
  backlinks: DocMeta[];
  tasks: Task[];
}
/**
 * Task is the API task shape.
 */
export interface Task {
  id: string;
  doc_path: string;
  doc_title: string;
  line: number /* int */;
  text: string;
  done: boolean;
  due: string | null;
  defer: string | null;
  priority: number /* int */;
  waiting: boolean;
  recur: string | null;
  project: string | null;
  tags: string[];
  completed_on: string | null;
}
/**
 * SearchResult is one search hit.
 */
export interface SearchResult {
  path: string;
  type: DocType | "task";
  title: string;
  snippet: string;
}
/**
 * Health is the unauthenticated liveness payload (also feeds the update
 * check and the version shown in Settings).
 */
export interface Health {
  status: string;
  version: string;
  update_available: boolean;
}
/**
 * ShareInfo is a share link as the API presents it. It lives here rather
 * than in internal/share so every response shape stays in one package —
 * that package is what generates the frontend's TypeScript types.
 */
export interface ShareInfo {
  token: string;
  doc_path: string;
  url: string;
  created_at: string;
  /**
   * Always sent (empty string = unset) rather than omitted: a key that
   * sometimes vanishes can't be typed honestly on the client.
   */
  expires_at: string;
  revoked_at: string;
  view_count: number /* int64 */;
  last_viewed_at: string;
}
/**
 * Birthday is an upcoming birthday surfaced on Today (within the next week
 * — the single-dad review's "1-week and day-of" requirement).
 */
export interface Birthday {
  path: string;
  title: string;
  date: string; // this year's occurrence, YYYY-MM-DD
  days_until: number /* int */;
  age: number /* int */ | null; // when the birthday year is known
}
/**
 * TodayPayload is the composed home-screen (and MCP `today` tool) response.
 */
export interface TodayPayload {
  date: string;
  daily: Document | null;
  meetings: DocMeta[];
  overdue: Task[];
  due_today: Task[];
  available: Task[];
  waiting: Task[];
  birthdays: Birthday[];
  recent: DocMeta[];
}
/**
 * Attachment is the upload response: the vault path and the markdown to
 * insert. References are vault-relative so they stay meaningful to external
 * editors; the SPA rewrites them to /api/v1/files/ URLs when rendering.
 */
export interface Attachment {
  path: string;
  markdown: string;
}
/**
 * RenameResult reports what a rename touched.
 */
export interface RenameResult {
  document: Document;
  rewritten: string[]; // docs whose links were updated
}
/**
 * CalendarDoc is a document touched on a day.
 */
export interface CalendarDoc {
  path: string;
  title: string;
  type: DocType;
}
/**
 * CalendarDay is one cell of the month grid.
 */
export interface CalendarDay {
  date: string; // YYYY-MM-DD
  /**
   * HasDaily reports whether a daily note exists for this date (whether or
   * not it was touched today — it is the day's anchor).
   */
  has_daily: boolean;
  touched: CalendarDoc[]; // documents modified that day
  meetings: CalendarDoc[]; // meetings scheduled that day
  completed_tasks: number /* int */;
}
/**
 * CalendarMonth is the month payload.
 */
export interface CalendarMonth {
  month: string; // YYYY-MM
  prev: string;
  next: string;
  days: CalendarDay[]; // every day of the month, in order
}
/**
 * AgentGuidanceResponse is the owner's MCP guidance and where it is stored.
 */
export interface AgentGuidanceResponse {
  /**
   * Path is the vault document holding it, so the UI can link to it.
   */
  path: string;
  text: string;
}
/**
 * TokenInfo is an API token as the management UI sees it. The token itself
 * is never here: only its 8-char display prefix, because the plaintext is
 * shown once at creation and only its hash is stored.
 */
export interface TokenInfo {
  id: number /* int64 */;
  name: string;
  prefix: string;
  scopes: string[];
  /**
   * Always sent (empty string = unset) so the client can type them
   * honestly — see ShareInfo.
   */
  created_at: string;
  expires_at: string;
  revoked_at: string;
  last_used_at: string;
}
/**
 * NewToken is the create response — the only time the plaintext exists
 * outside the caller's clipboard.
 */
export interface NewToken {
  token: TokenInfo;
  /**
   * Plaintext is shown once and never retrievable again.
   */
  plaintext: string;
}
/**
 * ConnectedApp is an OAuth client that has been granted access: what is
 * attached to this vault, with what scopes, and whether its grant is live.
 */
export interface ConnectedApp {
  client_id: string;
  name: string;
  scopes: string[];
  consented_at: string;
  last_used_at: string;
  active_grant: boolean;
}
/**
 * TagCount is a tag and how many documents carry it — the tags page.
 */
export interface TagCount {
  tag: string;
  count: number /* int */;
}
/**
 * AuditEntry is one recorded agent action. Human edits from the owner's own
 * browser session are not audited (they would drown the log in autosaves);
 * everything an API token or OAuth client does is.
 */
export interface AuditEntry {
  id: number /* int64 */;
  at: string;
  principal: string;
  /**
   * Action is the MCP tool name, or "METHOD /path" for a REST write.
   */
  action: string;
  /**
   * Path is the document the action touched, when there was one.
   */
  path: string;
  /**
   * Detail is a short human-readable summary (a title, a task's text).
   */
  detail: string;
  ok: boolean;
}
